### ISSUE TITLE
Set JAVA_HOME and JRE_HOME on the NetWorker Server by default

### ISSUE THREAD

**Issue by keilma** [bottkars/labbuildr#101]
Hi, 

nsrdr will not restore the authentication database when JAVA_HOME and JRE_HOME are not set, even if Java is in $PATH. Following error occurs:

'java' is not recognized as an internal or external command,
operable program or batch file.
C:\Program Files\EMC NetWorker\nsr\authc-server\tomcat\data\authcdb.h2.db -r 
C:\Program Files\EMC NetWorker\nsr\authc-server\tomcat\data\authcdb.h2.db: File exists, renaming to C:\Program Files\EMC NetWorker\nsr\authc-server\tomcat\data\~authcdb.h2.db
140071:nsrauthcasm: Unable to find JRE on this host
141612:nsrauthcasm: Unable to format Java path to launch authentication service recovery process: No such file or directory. Recovery process will attempt to locate the java binary in the PATH.
124433:nsrauthcasm: Restore of authc database from a temporary file 'C:\Program Files\EMC NetWorker\nsr\authc-server\tomcat\data\authcdb.R_000001' failed.
b.bak

After setting JAVA_HOME and JRE_HOME it works.

Kind regards
Marcel

**Comment by bottkars** [comment]
is this a bug ? 
the version of java to be taken shoulöd be choosen bei JRE for all programs, defined in java control panel.
setting JAVA_HOME and JRE_HOME would set a static path and is not update aware, and , in terms of java, do be defined by the use

However, i have a code that checks registry for the Pathn and set´s the variable for the User accordingly
Jou might give this a try : 
`[Environment]::SetEnvironmentVariable("JAVA_HOME",(Get-ItemProperty 'HKLM:\SOFTWARE\JavaSoft\Java Runtime Environment\1.8'  -PSProperty JavaHome).JavaHome, "User")
[Environment]::SetEnvironmentVariable("JRE_HOME",(Get-ItemProperty 'HKLM:\SOFTWARE\JavaSoft\Java Runtime Environment\1.8'  -PSProperty JavaHome).JavaHome, "User")
`
just considering putting it into a set-javaenvironment function / script that i place on the desktop ....
whats your take on that @keilma and @gaiswa

**Comment by keilma** [comment]
It's a requirement for NetWorker on Windows (also wasn't aware of this, I'm a Linux guy :)):

```
Add Java environment variables and modify PATH variable
On Windows, you must create the following Java environment variables in Control
Panel\System and Security\System\Advanced System Settings
\Advanced tab\Environment Variables button\System Variables in
order for NetWorker to install and start correctly:
l JAVA_HOME
l JRE_HOME
For their values, specify the path to the Java JRE folder. The default location for Java
7 versions is C:\Program Files\Java\jre7. The default location for Java 8
versions is C:\Program Files\Java\jre1.8.0_51.
Also, you must modify the PATH environment variable to add this value.
```

Found in the release notes of version 9.1.X.

**Comment by bottkars** [comment]
and even makes no sense for 9.1 to talk about  jre7, as 8 is required 👎 

> Supported Java versions
Java is not included with the NetWorker install. When installing the Console server
software, you must install the minimum required Java version. You cannot start NMC
until the appropriate JRE version is installed.
The minimum required version for NetWorker 9.1.x is 64-bit Java 8 update 60.


As i said, this method would not be Upgrade aware and is most likely a per-user / per shell setting IMHO

i would recommend to create a scheduled task that checks for java version all the time. more wordse than not having it is pointing to the wrong path as Machine or Service wide setting . Will throw a hint to engineering what´s that all about !

**Comment by bottkars** [comment]
added to install-java.ps1, that runs prior networker install. it is a dirty workaround, as windows uses the real path instead of symlinks

I thing the issue is that restore og authdb uses keytool.exe, wich is not linked to 

C:\ProgramData\Oracle\Java\javapath\


( hint: where java
C:\ProgramData\Oracle\Java\javapath\java.exe) gives you the symbolic link for java on windows
