### ISSUE TITLE
Wrong ValidateSet Attribute

### ISSUE THREAD

**Issue by keilma** [bottkars/labbuildr#102]
Hi, 

when running .\build-lab.ps1 -Blanknode -Master d I get the following masters:
```
"Das Argument "d" gehört nicht zu dem vom ValidateSet-Attribut angegebenen Satz
"2016TP5;2016TP5_GER;2016;2016core;2012R2_Ger;2012_R2;2012R2FallUpdate;2012R2Fall_Ger;2012_Ger;2012". Geben Sie ein Argument an, das in dem Satz enthalten ist, und führen Sie dann den Befehl erneut aus."
```

when running .\build-lab.ps1 -Blanknode -Master 2016TP5 -defaults I get this message:
```
"Das Argument für den Parameter "Master" kann nicht überprüft werden. Das Argument "2016TP5" gehört nicht zu dem vom ValidateSet-Attribut angegebenen Satz
"2016;2016core;2012R2_Ger;2012_R2;2012R2FallUpdate;2012R2Fall_Ger;2012_Ger;2012;OpenSUSE;openSUSE42_2;OpenWRT;Centos7_3_1611;Centos7_1_1511;Centos7_1_1503;Centos7"
```

Running .\build-lab.ps1 -Blanknode -Master 2016 -defaults works.
Complete output:
```
PS C:\MarcelKeil\labbuildr> .\build-lab.ps1 -Blanknode -Master d
C:\MarcelKeil\labbuildr\build-lab.ps1 : Das Argument für den Parameter "Master" kann nicht überprüft werden. Das Argument "d" gehört nicht zu dem vom ValidateSet-Attribut angegebenen Satz
"2016TP5;2016TP5_GER;2016;2016core;2012R2_Ger;2012_R2;2012R2FallUpdate;2012R2Fall_Ger;2012_Ger;2012". Geben Sie ein Argument an, das in dem Satz enthalten ist, und führen Sie dann den Befehl erneut aus.
In Zeile:1 Zeichen:36
+ .\build-lab.ps1 -Blanknode -Master d
+                                    ~
    + CategoryInfo          : InvalidData: (:) [build-lab.ps1], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,build-lab.ps1

PS C:\MarcelKeil\labbuildr> .\build-lab.ps1 -Blanknode -Master 2016TP5 -defaults
 ==>loading defaults from C:\MarcelKeil\labbuildr\defaults.xml
 ==>loading defaults from ./defaults.xml
==>Running labbuildr on a LENOVO 20BV004TGE with 1 x Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz with 2 Cores and 4 Logical CPUs and 16 GB Memory
Version 2017.Midsummer
 ==>Building Proposed Workorder
 ==>The Gateway will be 192.168.2.4
 ==>Entering Download Section
Test-LABmaster : Das Argument für den Parameter "Master" kann nicht überprüft werden. Das Argument "2016TP5" gehört nicht zu dem vom ValidateSet-Attribut angegebenen Satz
"2016;2016core;2012R2_Ger;2012_R2;2012R2FallUpdate;2012R2Fall_Ger;2012_Ger;2012;OpenSUSE;openSUSE42_2;OpenWRT;Centos7_3_1611;Centos7_1_1511;Centos7_1_1503;Centos7
Master;Ubuntu14_4;Ubuntu15_4;Ubuntu15_10;Ubuntu16_4;esximaster;photon-1.0-rev2". Geben Sie ein Argument an, das in dem Satz enthalten ist, und führen Sie dann den Befehl erneut aus.
```

Kind regards
Marcel

**Comment by bottkars** [comment]
What is -Master d ?

2016TP5 is no longer provided as download, thus 2016 or 2016core have to be used. the parameter is only there in build-lab for those who have that one specific master. however, they will be retired in next version

**Comment by keilma** [comment]
I just used -d to get all valid masters.
Is there another way to do this?
Why is for example 2016TP5 in the ValidateSet when running .\build-lab.ps1 -Blanknode -Master xyz and not when running .\build-lab.ps1 -Blanknode -Master 2016TP5 -defaults?

**Comment by bottkars** [comment]
there is no option -d. to get a list of valid Parameters, tab or use get-help build-lab.ps1 -Parameter Master
. 2016TP5 is/was there for those who have 2016TP5. The master i no longer available for download as the TP Version itself has expired. with latest update it should also be removed form the build-lab options

**Comment by bottkars** [comment]
`Get-Help .\build-lab.ps1 -Parameter master`

-Master <String>
    Wich version of OS Master should be installed
       '2016','2016core',#
       '2012R2_Ger','2012_R2',
       '2012R2FallUpdate','2012R2Fall_Ger',
       '2012_Ger','2012'

    Erforderlich?                false
    Position?                    named
    Standardwert
    Pipelineeingaben akzeptieren?false
    Platzhalterzeichen akzeptieren?false
