### ISSUE TITLE
Receive-LABBitsFile :  - An error occurred  downloading 'Exchange2013-x64-cu13.exe'

### ISSUE THREAD

**Issue by keilma** [bottkars/labbuildr#105]
Hi, 

labbuildr is unable to download Exchange 2013:

.\build-lab.ps1 -Exchange2013 -NMM -nmm_ver nmm9111

 ==>we are now Downloading C:\MarcelKeil\labbuildr\Sources\Exchange\E2013\Exchange2013-x64-cu13.exe from https://download.microsoft.com/download/7/4/9/74981C3B-0D3C-4068-8272-22358F78305F/Exchange2013-x64-cu13.exe, this may take a while
Start-BitsTransfer : HTTP-Status 404: Die angeforderte URL ist auf diesem Server nicht vorhanden.
In C:\MarcelKeil\labbuildr\labtools\labtools.psm1:1926 Zeichen:5
+ ...             Start-BitsTransfer -Source $DownLoadUrl -Destination $des ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-BitsTransfer], Exception
    + FullyQualifiedErrorId : StartBitsTransferCOMException,Microsoft.BackgroundIntelligentTransfer.Management.NewBitsTransferCommand

Receive-LABBitsFile :  - An error occurred  downloading 'Exchange2013-x64-cu13.exe'
In C:\MarcelKeil\labbuildr\labtools\labtools.psm1:3669 Zeichen:19
+ ...       if (!(Receive-LABBitsFile -DownLoadUrl $URL -destination $Downl ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Receive-LABBitsFile

WARNUNG: Error Downloading file https://download.microsoft.com/download/7/4/9/74981C3B-0D3C-4068-8272-22358F78305F/Exchange2013-x64-cu13.exe, Please check connectivity

PS C:\MarcelKeil\labbuildr> .\build-lab.ps1 -version
labbuildr version 2017-Autunum VMworld2017 Edition on branch : master
labbuildr Git Release  Mo, 18 Sep 2017 08:00:28 GMT
vmxtoolkit Git Release Sa, 30 Sep 2017 18:35:29 GMT
scripts Git Release  Mo, 18 Sep 2017 18:52:52 GMT
labtools Git Release  Mo, 18 Sep 2017 07:59:14 GMT

Kind regards
Marcel

**Comment by bottkars** [comment]
this is a N-2 Issue ....
from MS:
This update is no longer available because Cumulative Update 16 for Exchange Server 2013 (4012112) was released on March 21, 2017. You can install the latest Exchange Server 2013 update to fix the issues that are described in this article.

i did not Change the Code for that currently, because the Code honors local availabilty of the file.

I may add the description in later versions ...
