### ISSUE TITLE
LabDefaults are already set after installation

### ISSUE THREAD

**Issue by keilma** [bottkars/labbuildr#11]
Hi, 

you wrote the following on https://github.com/bottkars/labbuildr/wiki/1.0-Installation "6. verify defaults":

> take a look at you lab defaults. they should be empty
> 
> get-labdefaults  

That's not true:

> PS E:\labbuildr> Get-LABDefaults
> Master           : 2012R2FallUpdate
> ScaleIOVer       : 2.0-5014.0
> BuildDomain      : labbuildr
> MySubnet         : 192.168.2.0
> vmnet            : vmnet2
> vlanID           :
> DefaultGateway   : 192.168.2.4
> DNS1             : 192.168.2.4
> DNS2             : 192.168.2.10
> Gateway          : False
> AddressFamily    : IPv4
> IPV6Prefix       : FD00::
> IPv6PrefixLength : 8
> Sourcedir        : D:\sources
> SQLVer           : SQL2014
> e15_cu           : cu12
> e16_cu           : cu1
> NMM_Ver          : nmm9004
> NW_Ver           : nw9004
> NMM              : False
> Masterpath       :
> NoDomainCheck    :
> Puppet           :
> PuppetMaster     :
> HostKey          :

**Comment by bottkars** [comment]
Dokumentation will be changed. since 2016.spring release, a defaults.example will be populated if none found
