### ISSUE TITLE
==> Running labbuildr without OpenWRT, know what you do !

### ISSUE THREAD

**Issue by keilma** [bottkars/labbuildr#111]
Hi, 

I get this message when starting labbuildr:

==> Running labbuildr without OpenWRT, know what you do !

But OpenWRT is running and online:

![grafik](https://user-images.githubusercontent.com/13834137/34904527-02a7d5c4-f848-11e7-956c-6e33689eb151.png)
![grafik](https://user-images.githubusercontent.com/13834137/34904533-1b574802-f848-11e7-88d9-853564ba5dab.png)

Kind regards
Marcel

**Comment by keilma** [comment]
No gateway is configured on a fresh deployed DC:
![grafik](https://user-images.githubusercontent.com/13834137/34904551-53b2f44e-f848-11e7-9628-6962b1c3ffac.png)

**Comment by bottkars** [comment]
labbuild checks upon start for the value openwrt to be true. if this is false, labbuildr will not try to start openwrt by itself.

can you please paste your defaults.json in here ?

**Comment by bottkars** [comment]
default gateway fixed for -dconly on latest update, please share default json for -noopenwrt

**Comment by keilma** [comment]
Looks like it's gone after the update, before it worked.
openwrt is empty:

"OpenWRT":  "",

{
    "LanguageTag":  "de-DE",
    "TimeZone":  "W. Europe Standard Time",
    "Master":  "2012R2FallUpdate",
    "ScaleIOVer":  "2.0-6035.0",
    "BuildDomain":  "labbuildr",
    "Custom_DomainSuffix":  "local",
    "MySubnet":  "192.168.2.0",
    "vmnet":  "vmnet2",
    "vlanID":  "",
    "DefaultGateway":  "192.168.2.4",
    "DockerRegistry":  "",
    "APT_Cache_IP":  "",
    "DNS1":  "192.168.2.10",
    "DNS2":  "192.168.2.4",
    "Gateway":  "False",
    "AddressFamily":  "IPv4",
    "IPV6Prefix":  "FD00::",
    "IPv6PrefixLength":  "8",
    "Sourcedir":  "C:\\MarcelKeil\\labbuildr\\Sources",
    "SMBSourcedir":  "",
    "SQLVer":  "SQL2014SP2_ISO",
    "e14_ur":  "ur13",
    "e14_sp":  "sp3",
    "e15_cu":  "cu13",
    "e16_cu":  "cu2",
    "Server2016KB":  "",
    "NMM_Ver":  "nmm9010",
    "NW_Ver":  "nw9010",
    "NMM":  "False",
    "Masterpath":  "C:\\MarcelKeil\\labbuildr\\SharedMaster",
    "NoDomainCheck":  false,
    "OpenWRT":  "",
    "Puppet":  "",
    "PuppetMaster":  "",
    "HostKey":  "",
    "SMBPassword":  "",
    "SMBUsername":  "",
    "AnsiblePublicKey":  "",
    "MainMemUseFile":  ""
}

Just set it to true and everything is fine?

**Comment by bottkars** [comment]
just use Set-LABOpenWRT -enabled
