### ISSUE TITLE
UnityVSA Import fails - invalid target disk adapter type: PVSCSI

### ISSUE THREAD

**Issue by Munch05** [bottkars/labbuildr#113]
Having issues trying to import a Unity VSA appliance on VMware workstation Pro 14.
It does not like the PVSCSI adapter specified in the ovf/ova file and stops processing. As the script fails it does not output the files to the specified location.  See output below:

_PS C:\!labbuildr\Home> .\install-unity.ps1 -ovf C:\!Sources\EMC\UnityVSA\UnityVSA-4.3.0.1522077968.ova
 ==>loading defaults from ./defaults.json
 ==>Importing from OVA UnityVSA-4.3.0.1522077968, may take a while
Opening OVA source: C:\!Sources\EMC\UnityVSA\UnityVSA-4.3.0.1522077968.ova
The manifest does not validate
Opening VMX target: C:\!LabBuildr\Masters
Error: Invalid target disk adapter type: pvscsi
Deleting directory tree below: C:\!LabBuildr\Masters\UnityVSA-4.3.0.1522077968
Completed with errors
[success]
Use .\install-Unity.ps1 -Masterpath C:\!LabBuildr\Masters -Mastername UnityVSA-4.3.0.1522077968
        .\install-Unity.ps1 -Defaults to try defaults
OVA                       VMname                    Success
---                       ------                    -------
UnityVSA-4.3.0.1522077968 UnityVSA-4.3.0.1522077968    True_

If I use 7zip to extract the OVF files, I can amend the SCSI adapter type,  and can also update the md1 Hashs for the manifest file check to work, but not sure how I will get this to work with your script if I do?

**Comment by bottkars** [comment]
There is..... a install-unity-falcon.ps1 .... trief this one ?

Von meinem iPhone gesendet

Am 16.04.2018 um 11:21 schrieb Munch05 <notifications@github.com<mailto:notifications@github.com>>:


Having issues trying to import a Unity VSA appliance on VMware workstation Pro 14.
It does not like the PVSCSI adapter specified in the ovf/ova file and stops processing. As the script fails it does not output the files to the specified location. See output below:

_PS C:!labbuildr\Home> .\install-unity.ps1 -ovf C:!Sources\EMC\UnityVSA\UnityVSA-4.3.0.1522077968.ova
==>loading defaults from ./defaults.json
==>Importing from OVA UnityVSA-4.3.0.1522077968, may take a while
Opening OVA source: C:!Sources\EMC\UnityVSA\UnityVSA-4.3.0.1522077968.ova
The manifest does not validate
Opening VMX target: C:!LabBuildr\Masters
Error: Invalid target disk adapter type: pvscsi
Deleting directory tree below: C:!LabBuildr\Masters\UnityVSA-4.3.0.1522077968
Completed with errors
[success]
Use .\install-Unity.ps1 -Masterpath C:!LabBuildr\Masters -Mastername UnityVSA-4.3.0.1522077968
.\install-Unity.ps1 -Defaults to try defaults
OVA VMname Success

________________________________

UnityVSA-4.3.0.1522077968 UnityVSA-4.3.0.1522077968 True_

If I use 7zip to extract the OVF files, I can amend the SCSI adapter type, and can also update the md1 Hashs for the manifest file check to work, but not sure how I will get this to work with your script if I do?

**Comment by bottkars** [comment]
this is a knoiwn issue with the VMware ovatool. this is fixed in install-unity-falcon.ps1 ...

**Comment by Munch05** [comment]
Hi Karsten
Thanks for your reply, the suggestion of using the unity-falcon script resolved this. I had been perservering with the original unity script as all the documents and various google search results referenced this original script.
What a great suite of lab based products, will look back at them as the first call whenever I need to spin up an environment.
Thanks!
Steve

**Comment by bottkars** [comment]
Yes, that is still my Bad.... from Falcon release on i had to change the was i Attach disks... and with VMware 14 i Assed the ova Import bugfix... i will Remove the old and rename the Script soon ...

Von meinem iPhone gesendet

Am 18.04.2018 um 10:36 schrieb Munch05 <notifications@github.com<mailto:notifications@github.com>>:

Hi Karsten
Thanks for your reply, the suggestion of using the unity-falcon script resolved this. I had been perservering with the original unity script as all the documents and various google search results referenced this original script.
What a great suite of lab based products, will look back at them as the first call whenever I need to spin up an environment.
Thanks!
Steve
