### ISSUE TITLE
Expand-LAB7ZIP does not return an error when a file is not found

### ISSUE THREAD

**Issue by keilma** [bottkars/labbuildr#12]
Hi, 

no error is returned when a file for extracting is not found.

> PS E:\labbuildr> Expand-LAB7Zip -Archive D:\Lab\src\2012R2FallUpdateV1.7z
> PS E:\labbuildr>

Function Expand-LAB7Zip in labtools.psm1 should look like that:

```
function Expand-LAB7Zip
{
 [CmdletBinding(DefaultParameterSetName='Parameter Set 1',
    HelpUri = "https://github.com/bottkars/LABbuildr/wiki/LABtools#Expand-LABZip")]
    param (
        [string]$Archive,
        [string]$destination=$vmxdir
        #[String]$Folder
        )
    $Origin = $MyInvocation.MyCommand
    if (test-path($Archive))
    {
 #   If ($Folder)
 #      {
 #     $zipfilename = Join-Path $zipfilename $Folder
 #    }
        $7za = "$vmwarepath\7za.exe"

        if (!(test-path $7za))
            {
            Write-Warning "7za not found in $vmwarepath"
            }   
        Write-Verbose "extracting $Archive to $destination"
        if (!(test-path  $destination))
            {
            New-Item -ItemType Directory -Force -Path $destination | Out-Null
            }
        $destination = "-o"+$destination
        .$7za x $destination $Archive
    } else {
        Write-Warning "$Archive not found"
    }
}
```

That's also an idea for all other functions looking for some files.

Kind regards
Marcel

**Comment by bottkars** [comment]
some file checking as well a return codes from 7za.
however, as of current it is only a helper function with low priority

**Comment by bottkars** [comment]
check out new version now giving output object on success and returning error if file not found

`PS F:\EMCDEBlog> ipmo .\labtools -Force
PS F:\EMCDEBlog> Expand-LABZip -zipfilename C:\Users\Karsten\Downloads\CloudArray_ESXi5_7.0.0.0.8273.ova.7z
Expand-LABZip : Cannot validate argument on parameter 'zipfilename'. The " Test-Path -Path $_ -ErrorAction SilentlyContinue "
validation script for the argument with value "C:\Users\Karsten\Downloads\CloudArray_ESXi5_7.0.0.0.8273.ova.7z" did not return a
result of True. Determine why the validation script failed, and then try the command again.
At line:1 char:28
- Expand-LABZip -zipfilename C:\Users\Karsten\Downloads\CloudArray_ESXi5_7.0.0.0.8 ...
-                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidData: (:) [Expand-LABZip], ParameterBindingValidationException
  - FullyQualifiedErrorId : ParameterArgumentValidationError,Expand-LABZip

PS F:\EMCDEBlog> Expand-LAB7Zip -Archive C:\Users\Karsten\Downloads\CloudArray_ESXi5_7.0.0.0.8273.ova.zip -destination C:\Download
s

7-Zip (A) 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Processing archive: C:\Users\Karsten\Downloads\CloudArray_ESXi5_7.0.0.0.8273.ova.zip

file C:\Downloads\CloudArray_ESXi5_7.0.0.0.8273.ova
already exists. Overwrite with
CloudArray_ESXi5_7.0.0.0.8273.ova?
(Y)es / (N)o / (A)lways / (S)kip all / A(u)to rename all / (Q)uit? a
Extracting  CloudArray_ESXi5_7.0.0.0.8273.ova

Everything is Ok

Size:       690635264
Compressed: 657779935
Sucess expanding C:\Users\Karsten\Downloads\CloudArray_ESXi5_7.0.0.0.8273.ova.zip

Destination                                                      Archive

---

C:\Downloads                                                   C:\Users\Karsten\Downloads\CloudArray_ESXi5_7.0.0.0.8273.ova.zip`
