### ISSUE TITLE
How is the system evaluated?

### ISSUE THREAD

**Issue by keilma** [bottkars/labbuildr#14]
Hi, 

not urgent, but how du you evaluate the systen?

```
Bad, Running build-lab on a ASUS All Series with Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz with 4 Cores and 4 Logicalk CPUs and 16
GB Memory
```

Have seen worser hardware :)

Marcel

**Comment by bottkars** [comment]
It use to be a Math from i-Type and Memory But is already removed from early.summer expexct it to he completely removed, i did a vom sizing based on Memory But will remove that ..

**Comment by bottkars** [comment]
system evaluation is 1-8GB worse, 9 to 16, bad  17 - to 32 good
text reemove, only cound Mem and logical cpu
