### ISSUE TITLE
Building SQL Lab / labbuildr installs nw9004 and nmm9006

### ISSUE THREAD

**Issue by keilma** [bottkars/labbuildr#15]
Hi,  

I've two nw versions in my source directory:

nw9004 + nw9006

When running ".\build-lab.ps1 -SQL -SQLVER SQL2014 -NMM -nmm_ver **nmm9006** -defaults" NW client **9004** is installed on the SQL host. NMM is installed in version **9006** like specified.

It should be a dependency to install the same version of the NW client when a nmm version is specified, even when the NW version is not provided to build-lab.ps1.

What do you think? Why is 9004 installed?

Regards
Marcel

**Comment by bottkars** [comment]
Mostbprobably your nw_version is at 9004. labbuildr selects the nw_version for nwserver and Client as they See Independant from nmm ( wich is an Option only )
