### ISSUE TITLE
Installing SSMS plugin during NMM installation

### ISSUE THREAD

**Issue by keilma** [bottkars/labbuildr#20]
Hi, 

what do you think about installing the SSMS plugin when installing NMM < 9.X on a SQL host?

The following parameter should do it: NW_SSMS_FEATURE=1

When installing 9.X you already activate it.

Kind regards
Marcel

**Comment by bottkars** [comment]
There is a difference between should and diD . Have hat so many issues in the 8,x with the unattended setting. had it on the radar to debug what the installeris doing. It is a mixture of issues from installer verion / sql version and atual user rights. will double ceck on that
