### ISSUE TITLE
Exchange 2013 ECP/OWA not working after deployment

### ISSUE THREAD

**Issue by keilma** [bottkars/labbuildr#22]
Hi, 

when deploying Exchange 2013 CU 12 (tested with single node and DAG)  and pointing the browser to https://localhost/ecp/?ExchClientVer=15 I only get a 404.

```
ModuleIIS Web Core 
Notification MapRequestHandler 
Handler StaticFile 
Error Code 0x80070002 
Requested URL https://localhost:443/ecp/?ExchClientVer=15 
Physical Path C:\inetpub\wwwroot\ecp\ 
Logon Method Anonymous 
Logon User Anonymous 
```

The physical path irritates me.
Still trying to figure out what is going wrong.

Any suggestions?

Kind regards
Marcel

**Comment by keilma** [comment]
Client Access Role was not installed, works now.
Is there a reason why this role is not installed during deployment?

`$ArgumentLst = "/mode:Install /role:Mailbox /OrganizationName:`"$Env:USERDOMAIN`" /IAcceptExchangeServerLicenseTerms /MdbName:$DB1 /DbFilePath:$ExDatabasesBase\DB1\DB1.DB\DB1.EDB /LogFolderPath:$ExDatabasesBase\DB1\DB1.LOG"`

**Comment by bottkars** [comment]
thanks for cathcing up on this. might be relate to to many drugs in hospital :-)

blamed cu12 first on it. fixed now. also added cu13 support
