### ISSUE TITLE
Everytime running build-lab.ps1 -Update it finds an vmxtoolkit update

### ISSUE THREAD

**Issue by keilma** [bottkars/labbuildr#23]
Hi,

when I run build-lab.ps1 -Update in succession it finds every time an update for vmxtoolkit but does not install anything.

PS E:\labbuildr> .\build-lab.ps1 -Update
 ==>No update required for labbuildr on master, already newest version
 ==>No Deletions required
 ==>No update required for labbuildr-scripts on master, already newest version
 ==>No update required for labtools on master, already newest version
**We found a newer Version for vmxtoolkit on Git Dated Tue, 05 Jul 2016 19:01:08 GMT
 ==>extracting E:\labbuildr\update\vmxtoolkit-master.zip\vmxtoolkit-master to E:\labbuildr\vmxtoolkit
 ==>No update required for SIOToolKit on master, already newest version**
 ==>Update Done
 ==>press any key for reloading Modules

**Comment by bottkars** [comment]
tanks for catching up on this. hat a recent change to slim down the code, and did not fix a static variable.

shut work now. in case it does not ubdate, force the update with -force
