### ISSUE TITLE
Install NMM with GLR option enabled

### ISSUE THREAD

**Issue by keilma** [bottkars/labbuildr#25]
Hi, 

NMM GLR is not enabled when installing NMM during deployment.

> setup.exe /s /v"/qn /l_v setup.log INSTALLLEVEL=200
> REBOOTMACHINE=1 NW_GLR_FEATURE=1 WRITECACHEDIR "C:\Program
> Files\EMC NetWorker\nsr\tmp\nwfs" MOUNTPOINTDIR "C:\Program Files
> \EMC NetWorker\nsr\tmp\nwfs\NetWorker Virtual File System"
> HYPERVMOUNTPOINTDIR "C:\Program Files\EMC NetWorker\nsr\tmp"
> SETUPTYPE=Install"
> Ensure that there is a space between:
> l setup and /s
> l /s and /v”/qn
> l /v”/qn” and /l_v
> l /l*v and setup.log
> l setup.log and INSTALLLEVEL=200
> l INSTALLLEVEL=200 and REBOOTMACHINE=1
> l REBOOTMACHINE=1 and NW_GLR_FEATURE=1
> l NW_GLR_FEATURE=1 and WRITECACHEDIR
> l WRITECACHEDIR and "C:\Program Files\EMC
> l NetWorker\nsr\tmp\nwfs"
> l "C:\Program Files\EMC
> l NetWorker\nsr\tmp\nwfs" and MOUNTPOINTDIR
> l MOUNTPOINTDIR and "C:\Program Files\EMC
> l NetWorker\nsr\tmp\nwfs\NetWorker Virtual File System"
> l "C:\Program Files\EMC
> l NetWorker\nsr\tmp\nwfs\NetWorker Virtual File System" and
> HYPERVMOUNTPOINTDIR
> l HYPERVMOUNTPOINTDIR and "C:\Program
> l Files\EMC NetWorker\nsr\tmp"
> l "C:\Program Files\EMC NetWorker\nsr\tmp" and SETUPTYPE=Install

Needed for Exchange/Sharepoint/Hyper-V

**Comment by bottkars** [comment]
glr on NMM8 needs to install eldos driver. however, this does not work / is not supported unattended.

did not follow on this due to nmm9 using iscsi
