### ISSUE TITLE
NMMBackupUser mailbox is not activated

### ISSUE THREAD

**Issue by keilma** [bottkars/labbuildr#27]
Hi, 

to use GLR the mailbox of the user used for backup and restore (NMMBackupUser) has to be activated - received a mail or logged in via OWA. That not happens during deployment, so GLR operations will fail.

After logging in into OWA GLR works.

Marcel

**Comment by bottkars** [comment]
is there a mail in the inbox of nmmbackupuser ? if not , attachements to send where not found. trying now  fix with mailbody only. the userscript noramlyy sends an attachement to EVERY user

**Comment by bottkars** [comment]
you should have this message in your inbox 
![image](https://cloud.githubusercontent.com/assets/8255007/16716017/9cdbfd88-46f0-11e6-8b21-7d4a8d5c8ad2.png)

**Comment by keilma** [comment]
There was no mail.
Will check it again, thank you.

**Comment by keilma** [comment]
got mail :)
