### ISSUE TITLE
Script Failure - VPN issue

### ISSUE THREAD

**Issue by keilma** [bottkars/labbuildr#28]
Hi, 

I vaguely remember that I already had this problem in the past, but I don't remember the solution anymore.
Deploying Sharepoint:

`18 .\build-lab.ps1 -defaults -Sharepoint -SQLVER "SQL2014" -NMM -nmm_ver nmm8232 -NW -nw_ver nw8232`

I get this message when NW client should be installed:

```
WARNING: Script Failure for install-nwclient.ps1 with Guest program exited with non-zero exit code: 1

Scriptfailure for install-nwclient.ps1
May be VPN Issue, retry ?
[Y] Yes  [N] No  [A] Abort  [?] Help (default is "Y"): y
```

What is going wrong? Are there any logfiles?
Searched for "VPN" in some scripts but didn't find anything.

Marcel

**Comment by bottkars** [comment]
the message comes from vmxtoolkit and most likely indicates the script could not run. ( only 0 or 1 get returned ) try to run the script again from tkat point with y. if it still fails, go into the vm and try to run it from the labbuildr  prompt. send me the errro

**Comment by bottkars** [comment]
could be an issue fro codecleanin, as i do not pas the nw_ver correctly. fixed in latest commit

**Comment by bottkars** [comment]
sorry, it is notmy code in build-lab, need to investigate

**Comment by bottkars** [comment]
a wrong script path was passed in the call. fixed
