### ISSUE TITLE
Exchange permissions are not set correctly

### ISSUE THREAD

**Issue by keilma** [bottkars/labbuildr#50]
Hi, 

when deploying an Exchange 2013 CU 13 DAG (2 nodes), the permissions for the NMMBackupUser are not set correctly. I don't know which permission is missing, but the NMM Exchange Admin Configuration Tool fixed it (I'm loving this tool :)).

Just run the tool on both nodes -> Configure Admin User -> Configure existing user -> enter nmmbackupuser and it will set all necessary permissions.

Unfortunately, it does not display which permission is missing when running the check.

Marcel

**Comment by keilma** [comment]
Running labbuildr version 2016-3rd Anniversary on branch : master

**Comment by bottkars** [comment]
marcel, they removed the cli tool do do so from the beta. this is a manual task to do unfortunately, as som stuff is stored in the local registry :-(
