### ISSUE TITLE
Adding users to the NW administrators when deploying a node after initial NW deployment

### ISSUE THREAD

**Issue by keilma** [bottkars/labbuildr#56]
Hi, 

I've the following lab:
- DC
- NW
- Exchange 2016

After playing around I decided to add a Hyper-V VM (.\build-lab.ps1 -HyperV ... -defaults).
When deploying a node after the initial NW deployment NetWorker permissions are not added and it has to be done manually (nsraddadmin -u "user=SYSTEM,host=hypernode").

Maybe it's an idea for an improvement: everytime adding a node also add it's users to the NW administrators. 

Marcel

**Comment by bottkars** [comment]
Marcel, have a look into scripts/nwserevr and you will fin NICE Things ;.)
i recommend checking out 
sripts\nwserver\add-nsruser.ps1 [-BackupAdmin] <Object> [-Hostprefix]
eg add-nsruser.ps1 -BackupAdmin HVBackupUser -Hostprefix HV*
this will add all required users

also, check out the hyperv directory for 
configure-hyperv.ps1
- -csvbackupuser.ps1
- new-clusteredvm.ps1
