### ISSUE TITLE
CentOS Master download not working

### ISSUE THREAD

**Issue by keilma** [bottkars/labbuildr#57]
Hi, 

when running install-centos.ps1 the master is not downloaded automatically:

> PS C:\labbuildr> .\install-centos.ps1 -Defaults -centos_ver 7
>  ==>Loading defaults from .\defaults.xml
> WARNUNG: Required Master Centos Master not found
>     please download and extraxt Centos Master to .\Centos Master
>     see:
>     ------------------------------------------------
>     get-help install-centos.ps1 -online
>     ------------------------------------------------

Online help says the master will be downloaded:

https://github.com/bottkars/labbuildr/wiki/install-centos.ps1
"this will launch the centos install. if no master is available for $MasterPath, labbuildr will ask for download ( remember, -confirm:$false will do without asking )"

**Comment by keilma** [comment]
-forcedownload does also not work

**Comment by bottkars** [comment]
duplicate
