### ISSUE TITLE
Labbuildr does not recognize existent CentOS master

### ISSUE THREAD

**Issue by keilma** [bottkars/labbuildr#58]
Hi, 

install-centos.ps1 does not recognize that I already downloaded the master for CentOS:

```
PS C:\labbuildr> .\install-centos.ps1 -Defaults -centos_ver 7
==>Loading defaults from .\defaults.xml
WARNUNG: Required Master Centos Master not found
```

> PS C:\labbuildr> Get-LABDefaults
> ..
> Masterpath          : C:\labbuildr\SharedMaster
> ..
> 
> PS C:\labbuildr> ls .\SharedMaster\
> 
> ```
> Verzeichnis: C:\labbuildr\SharedMaster
> ```
> 
> Mode                LastWriteTime         Length Name
> ---
> 
> d-----       30.08.2016     09:09                2012R2FallUpdate
> d-----       12.08.2016     17:15                CentOS7 Master

**Comment by bottkars** [comment]
fixed now. however, i would encurage to use 7_1511 version of centos
