### ISSUE TITLE
Password for DDWRT

### ISSUE THREAD

**Issue by keilma** [bottkars/labbuildr#59]
Hi, 

which password is set for the root account?
It's not mentioned here: https://github.com/bottkars/labbuildr/wiki/Student-Guide

The default DDWRT root "admin" does not work - can't login into the webinterface.
I tried also "password" and "root"

Marcel

**Comment by keilma** [comment]
Have set it with passwd.

**Comment by bottkars** [comment]
Password123! is standard for labbuildr admin passwords in every deployment
