### ISSUE TITLE
IP addresses for CentOS

### ISSUE THREAD

**Issue by keilma** [bottkars/labbuildr#60]
Hi, 

my deployed CentOS Node got IP 192.168.2.206 and not 192.168.2.22X

https://github.com/bottkars/labbuildr/wiki/IP-Addresses

DNS points to .206 for the first node.

Marcel

**Comment by bottkars** [comment]
dioku is outdated at this point, those have been special nodes for ScaleIO with centos and are deprectated. From Testing on wards, you are free to give your own range
