### ISSUE TITLE
CentOS hostnames

### ISSUE THREAD

**Issue by keilma** [bottkars/labbuildr#61]
Hi, 

after deployment the hostname is still "localhost.localdomain"
labbuildr showed success on changing it:

==>running sed -i -- '/HOSTNAME/c\HOSTNAME=CentosCentos1' /etc/sysconfig/network on: Centos1[success]

/etc/sysconfig/network is empty. 

Maybe hostnamectl is a better way: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Networking_Guide/sec_Configuring_Host_Names_Using_hostnamectl.html

Marcel

**Comment by bottkars** [comment]
hostnamectl, for whatever reason, does not work remotely :-( vi vix from centos .

however, this as already been addressed and fixed in testing branch by using nmcli.
