### ISSUE TITLE
Add additional GENNode after already deployed one

### ISSUE THREAD

**Issue by keilma** [bottkars/labbuildr#62]
Hi, 

I've deployed one GENNode and now I've decided to deploy an additional one:

PS C:\keilma\labbuildr> .\build-lab.ps1 -Blanknode -BlankNodes 1 -defaults -
Size M
**WARNUNG: GENNode1 already exists**

When running with -BlankNodes 2 the second node is deployed.
Just an improvement: would be nice when build-lab.ps1 checks that there is already a node and then deploys a second one (GENNode2).

Marcel

**Comment by bottkars** [comment]
nope. wont do this. check parameters for blankstart ... that indicates the node to start wit.
so -blanknodes 1 -blankstart 2 will get you there
