### ISSUE TITLE
Installation of Opensack Ubuntu fails at configuring and restarting the SDC

### ISSUE THREAD

**Issue by davestemerdink** [bottkars/labbuildr#68]
Ubuntu-bakery.ps1 is failling after running the command on line number 691:

"/usr/bin/dos2unix /bin/emc/scaleio/scini_sync/driver_sync.conf;/etc/init.d/scini restart")

![crash](https://cloud.githubusercontent.com/assets/7320789/19237235/310944b8-8efc-11e6-8020-08325a838042.PNG)

**Comment by bottkars** [comment]
Wow, looks more like a sddc bug to me :-)..  can youcheckbthe kernel version you are on / sio version ?

**Comment by davestemerdink** [comment]
yeah, it's running 14.04 and SIO 2.0.0.2.. Im trying the testing/develop branches now :-)

**Comment by bottkars** [comment]
could not reproduce, need more information going forward
