### ISSUE TITLE
Exchange 2013: cu14 is missing in ValidateSet Attribut

### ISSUE THREAD

**Issue by keilma** [bottkars/labbuildr#69]
Hi, 

default for e15_cu is cu14:

get-labdefaults

e15_cu              : cu14

But it's not valid:

Receive-LABExchange : Das Argument für den Parameter "e15_cu" kann nicht überprüft werden. Das Argument "cu14" gehört nicht zu dem vom ValidateSet-Attribut angegebenen Satz "cu1;cu2;cu3;sp1;cu5;cu6;cu7;cu8;cu9;cu10;cu11;cu12;cu13". Geben Sie ein Argument an, das in dem Satz
enthalten ist, und führen Sie dann den Befehl erneut aus.
In C:\MarcelKeil\labbuildr_cv\build-lab.ps1:2048 Zeichen:53

If (!(Receive-LABExchange -Exchange2013 -e15_cu $e15_cu -Destinat ...
                                                  ~~~~~~~
    CategoryInfo          : InvalidData: (:) [Receive-LABExchange], ParameterBindingValidationException
    FullyQualifiedErrorId : ParameterArgumentValidationError,Receive-LABExchange

labbuildr version 2016-3rd Anniversary SP1 on branch : master
labbuildr Git Release 11/01/2016 11:19:05
vmxtoolkit Git Release 10/28/2016 07:57:20
scripts Git Release 11/01/2016 11:19:53
labtools Git Release 10/31/2016 05:39:24

**Comment by bottkars** [comment]
thanks for bringing up
validate set now aligned to match global replace
