### ISSUE TITLE
Error: Incorrect command line when extracting a master after fresh install

### ISSUE THREAD

**Issue by keilma** [bottkars/labbuildr#78]
Hi, 

after a fresh installation and when trying to rollout a master I get this message:

 ==>extracting D:\Lab\Labbuildr\Master.labbuildr\2012R2FallUpdate.7z to D:\Lab\L
abbuildr\Master.labbuildr
 ==>Using C:\Program Files (x86)\VMware\VMware Workstation\7za.exe with x -bb0 -
bso0 -bsp0 -oD:\Lab\Labbuildr\Master.labbuildr D:\Lab\Labbuildr\Master.labbuildr
\2012R2FallUpdate.7z

Error:
Incorrect command line
 ==>Sucess expanding D:\Lab\Labbuildr\Master.labbuildr\2012R2FallUpdate.7z

--

 ==>extracting D:\Lab\Labbuildr\OpenWRT_15_5_1.7z to ./
 ==>Using C:\Program Files (x86)\VMware\VMware Workstation\7za.exe with x -bb0 -
bso0 -bsp0 -o./ D:\Lab\Labbuildr\OpenWRT_15_5_1.7z

Error:
Incorrect command line

**Comment by keilma** [comment]
PS D:\Lab\Labbuildr> .\build-lab.ps1 -version
labbuildr version 2016-3rd Anniversary SP1 on branch : master
labbuildr Git Release  Fr, 06 Jan 2017 07:18:06 GMT
vmxtoolkit Git Release Mo, 21 Nov 2016 09:02:21 GMT
scripts Git Release  Fr, 23 Dez 2016 13:46:14 GMT
labtools Git Release  Sa, 31 Dez 2016 05:40:10 GMT

**Comment by bottkars** [comment]
what Version of vmware Workstation are you using ?

**Comment by bottkars** [comment]
should be fixed now if using VMware older 12.5 ...

**Comment by keilma** [comment]
Running version 11.1.3 ;-)

**Comment by bottkars** [comment]
can you please try with latest build-lab.ps1  update followed by receive-labopenwrt -start ?

**Comment by keilma** [comment]
Works now - thanks a lot :)
