### ISSUE TITLE
Scriptfailure for install-exchangeprereqs.ps1 / May be VPN Issue, retry ?

### ISSUE THREAD

**Issue by keilma** [bottkars/labbuildr#79]
Hi Karsten, 

when installing Exchange 2016 I get the following message:

Scriptfailure for install-exchangeprereqs.ps1
May be VPN Issue, retry ?

Retry does not help. Running the script inside the VM works.

Marcel

**Comment by bottkars** [comment]
@keilma what version of GuestOS, and  what version of Exchange are you installing ? Are you using UNC to install or standard method ? (edited)

**Comment by keilma** [comment]
Hi, 

Server 2012 R2, Exchange 2016.
I'm used the standard method.

**Comment by bottkars** [comment]
just tested this one with 2016 ( cu4) and works as designed. did you test retry after vpn issue ? did you update Firewall Software ( aka McAfee )

**Comment by keilma** [comment]
Retry did not work.
Only the windows firewall is running and there was no change.

All steps before and after running the script inside the VM worked.
No problems with DC/NW Server.

**Comment by bottkars** [comment]
no probölems on several test machines . will close until error opens again
