### ISSUE TITLE
Expand-LAB7Zip  ==>expand exited with code 2

### ISSUE THREAD

**Issue by keilma** [bottkars/labbuildr#80]
Hi, 

when using Expand-LAB7Zip for extracting the DDMC OVA I get the following message:

PS C:\MarcelKeil\labbuildr\Sources> Expand-LAB7Zip '.\ddmc-2.0.0.1-550693-vcenter.zip' -destination  DDMC2001
 ==>extracting .\ddmc-2.0.0.1-550693-vcenter.zip to DDMC2001

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21

Scanning the drive for archives:

ERROR: Das System kann die angegebene Datei nicht finden.
 -oDDMC2001

System ERROR:
Das System kann die angegebene Datei nicht finden.
 ==>expand exited with code 2

PS C:\MarcelKeil\labbuildr\Sources> Expand-LAB7Zip '.\ddmc-2.0.0.1-550693-vcenter.zip' -destination " DDMC2.0.0.1"
 ==>extracting .\ddmc-2.0.0.1-550693-vcenter.zip to  DDMC2.0.0.1

7-Zip (a) [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21

Scanning the drive for archives:

ERROR: Das System kann die angegebene Datei nicht finden.
 -o DDMC2.0.0.1

System ERROR:
Das System kann die angegebene Datei nicht finden.
 ==>expand exited with code 2

Manual extract + install works.
VMware Workstation 12.5.2.

Kind regards
Marcel

**Comment by bottkars** [comment]
destination must be a valid path, eg .\DDMC2.0.1

**Comment by bottkars** [comment]
ps: try install-ddmc.ps1
