### ISSUE TITLE
Creating a node without joining the domain

### ISSUE THREAD

**Issue by keilma** [bottkars/labbuildr#84]
Hi, 

what do you think about a parameter to create a node without joining the domain? Need and already needed this for some tests. The only parameter I found is this one:

 -NoDomainCheck [<SwitchParameter>]
        network Parameters ######
        Disable Domainchecks for running DC
        This should be used in Distributed scenario´s

That's not exactly what I need.

Kind regards
Marcel

**Comment by bottkars** [comment]
This could be done by a single line with vmxtoolkit 👍 
`get-vmx -path C:\Users\KarstenBott\Master.labbuildr\2016core\ | Get-VMXSnapshot | ? Snapshot -Match BASE | New-VMXLinkedClone -CloneName test | start-vmx`

whatr is the requirement ?

**Comment by bottkars** [comment]
however, we vae a set of labtools command doing that for ubuntu and centos ( new-labvmx and set-labvmx ) that configure the vm up to the ip and optional packackes. currently thinking ov doing that for woindows up to roles / feature

**Comment by keilma** [comment]
Would be nice.
I used build-lab.ps1 to build some blank nodes and removed them from the domain by hand.

Thanks for the oneliner.

**Comment by bottkars** [comment]
functionslity is now provided with new-labvvmx and set-labwindowsvmx in dev branch
