### ISSUE TITLE
labbuildr openstack

### ISSUE THREAD

**Issue by Nickske157** [bottkars/labbuildr#85]
Hi, there are issues when I try to install an openstack lab.

WARNING: Script Failure for MDM_ROLE_IS_MANAGER=1 dpkg -i
/mnt/hgfs/Sources/ScaleIO/ScaleIO_linux_SW_Download/ScaleIO_2.0.1.2_Complete_Linux_SW_Download/ScaleIO_2.0.1.2_UBUNTU_1
4.04_Download/EMC-ScaleIO-mdm*.deb >> /tmp/labbuildr.log 2>&1 with Guest program exited with non-zero exit code: 1

Scriptfailure for MDM_ROLE_IS_MANAGER=1 dpkg -i
/mnt/hgfs/Sources/ScaleIO/ScaleIO_linux_SW_Download/ScaleIO_2.0.1.2_Complete_Linux_SW_Download/ScaleIO_2.0.1.2_UBUNTU_1
4.04_Download/EMC-ScaleIO-mdm*.deb >> /tmp/labbuildr.log 2>&1
May be VPN Issue, retry ?
[Y] Yes  [N] No  [A] Abort  [?] Help (default is "Y"):

When I check the Source directory in that specified directory, there are no deb files
PS C:\Users\LabBuilder> Get-ChildItem -Path C:\Users\LabBuilder\Sources.labbuildr\ScaleIO\ScaleIO_linux_SW_Download\
ScaleIO_2.0.1.2_Complete_Linux_SW_Download\ScaleIO_2.0.1.2_UBUNTU_14.04_Download

    Directory: C:\Users\LabBuilder\Sources.labbuildr\ScaleIO\ScaleIO_linux_SW_Download\ScaleIO_2.0.1.2_Complete_Linux
    _SW_Download\ScaleIO_2.0.1.2_UBUNTU_14.04_Download

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
------       29/12/2016     15:11        7536640 EMC-ScaleIO-lia-2.0-12000.122.Ubuntu.14.04.x86_64.tar
-a----       29/12/2016     15:11       15114240 EMC-ScaleIO-mdm-2.0-12000.122.Ubuntu.14.04.x86_64.tar
------       29/12/2016     15:11        4843520 EMC-ScaleIO-sdc-2.0-12000.122.Ubuntu.14.04.x86_64.tar
------       29/12/2016     15:11        7485440 EMC-ScaleIO-sds-2.0-12000.122.Ubuntu.14.04.x86_64.tar
------       29/12/2016     15:11        7475200 EMC-ScaleIO-sds1-2.0-12000.122.Ubuntu.14.04.x86_64.tar
------       29/12/2016     15:11        8325120 EMC-ScaleIO-sds2-2.0-12000.122.Ubuntu.14.04.x86_64.tar
------       29/12/2016     15:11        8325120 EMC-ScaleIO-sds3-2.0-12000.122.Ubuntu.14.04.x86_64.tar
------       29/12/2016     15:11        7495680 EMC-ScaleIO-sds4-2.0-12000.122.Ubuntu.14.04.x86_64.tar
------       29/12/2016     15:11         276480 EMC-ScaleIO-xcache-2.0-12000.122.Ubuntu.14.04.x86_64.tar
------       29/12/2016     15:11          20642 EMC_ScaleIO_Software_Agreement.txt

Kind Regards

Nick Geoffroy

**Comment by bottkars** [comment]
yes, this is an known issue that siob files could not be extracted with 2.0.1, as somebody put them in to tar files in addition . ( so i need to extrac the package, untar the siob files and san do a siob extract on the siob files ) i fixed this with develop branch. if you want to give it a try, do a build-lab.ps1 -update -branch develop. this his going to be releases soon ...

**Comment by Nickske157** [comment]
Hi,
Your fix worked flawless, openstack is continuing, thanks for the quick support.

Kind Regards
Nick Geoffroy
