### ISSUE TITLE
Exchange 2013 CU13 not found

### ISSUE THREAD

**Issue by keilma** [bottkars/labbuildr#97]
Hi Karsten, 

when deployging Exchange 2013 with -defaults (CU13) I get a 404:

 ==>we are now Downloading C:\MarcelKeil\labbuildr\Sources\Exchange\E2013\Exchange2013-x64-cu13.exe from https://download.microsoft.com/download/7/4/9/74981C3B-0D3C-4068-8272-22358F78305F/Exchange2013-x64-cu13.exe, this may take a while
Start-BitsTransfer : HTTP-Status 404: Die angeforderte URL ist auf diesem Server nicht vorhanden.

Download with CU15 works.

Kind regards
Marcel

**Comment by bottkars** [comment]
not a bug. Exchange CU´s will be removed from dowload.microsoft.com when n-2

**Comment by keilma** [comment]
Ok, I wasn't aware of this.
Why not printing a short message when this is the case or preventing labbuildr from downloading such old versions?
