### ISSUE TITLE
Type System.String cannot be converted to type System.Collections.ArrayList

### ISSUE THREAD

**Issue by keilma** [bottkars/labbuildr#98]
Hi, 

during deployment of two Exchange nodes I get this error:

![grafik](https://user-images.githubusercontent.com/13834137/27819923-aba1c2b4-609c-11e7-911f-c14c51328fa7.png)

Kind regards
Marcel

**Comment by bottkars** [comment]
what Version of VMware are you running ?
does Setup continue from that step ? ( the process is waiting for Tools running and Looks like the return value is not initialized properly )

**Comment by keilma** [comment]
VMware Workstation 12.5.7.
Setup does continue.

**Comment by bottkars** [comment]
vixed with new version
